#+TITLE:  On *planned* mass murders on the territory of Ukraine
#+AUTHOR: Mykola Stryebkov
#+LATEX_HEADER: \usepackage[utf8]{inputenc}
#+LATEX_HEADER: \usepackage[T2A]{fontenc}
#+LATEX_HEADER: \usepackage[english,ukrainian]{babel}
#+LATEX_HEADER: \usepackage{lcy}
#+LATEX_HEADER: \usepackage{textcomp}
#+LATEX_HEADER: \usepackage[margin=2cm]{geometry}

* Executive summary

The mass killings of Ukrainian citizens by the Russian invasion forces are
the result of a *pre-planned operation aimed at physical
extermination of the socially active stratum of Ukrainian society*.

Russians are eager for such social purges, in particular, because of
many years of state propaganda in the Russian Federation and the
invariability of the modus operandi of Russians in Ukraine for the
last century.

* The Evidence

** Uniformity of executions
The similarity and uniformity of executions of different people in
different settlements indicates their implementation according to a
single methodology.

Thus, among the mass killings of civilians in the Kyiv region, the
killings of people - mostly military-aged men - with their hands tied
behind their backs and a bullet hole in the back of the head stand
out.

Task: to check the existence of relevant methodological literature in
the RF military or security agencies.

** GOST R (National Standard) 42.7.01-2021 for mass burial

The new GOST of the Russian Federation on mass burials was adopted in
Sep 21, 2021 and entered into force on Feb 1, 2022, a little more
than 3 weeks before the start of the open war: [[https://docs.cntd.ru/document/1200180859][NATIONAL STANDARD OF
THE RUSSIAN FEDERATION. URGENT BURIAL OF CORPSES IN WAR AND PEACE]], [[https://web.archive.org/web/20220402173717/https://docs.cntd.ru/document/1200180859][Web
Archive]].

Task: to check the size of the mass grave in Bucha. According to their
standard should be:
- 20m - length at the bottom
- 3m - width
- 2.3m - depth.
- 32m - at the top, taking into account the slopes for the departure
  of the tractor.

** Mobile crematoria

They were intended to avoid the burial of prominent public figures of
Ukraine, because burial sites eventually become "places of pilgrimage"
(modus operandi similar to the murder of Roman Shukhevych, see below).

The day before the invasion the Defence Secretary of the
United Kingdom Ben Wallace stated about the preparation of mobile
crematoria for the Russian army's invasion in Ukraine. This was
mentioned, in particular, in [[https://www.telegraph.co.uk/world-news/2022/02/23/russia-deploys-mobile-crematorium-follow-troops-battle/][The Telegraph]], ([[https://web.archive.org/web/20220331033347/https://www.telegraph.co.uk/world-news/2022/02/23/russia-deploys-mobile-crematorium-follow-troops-battle/][Web Archive]]). However,
Mr. Walles erroneously decided that with help of the crematoria the
Russian army was going to cover up its own losses.

The following facts could serve as a confirmation of the thesis that
the crematoria were not intended for Russian soldiers:
- on the spots where the Russian army generally collected its corpses,
  they had arranged the ways of their transportation outside of
  Ukraine.
- use of portable crematoria for mass cremation of bodies is
  inefficient because of the characteristics stated by the the
  [[http://turmalin.su/index.php?option=com_content&view=article&id=185&Itemid=331][manufacturer]]:
#+BEGIN_QUOTE
When used for ritual purposes:
- time of full cremation of one object: about 1 hour
- unloading of ashes is automated
- cremation
- system of additional dust cleaning
- 15-16 liters of diesel fuel or 20 m3 of natural gas for cremation of one object
#+END_QUOTE

** 45,000 bags for corpses

The bags were intended for the citizens of Ukraine.

If bags were intended for corpses of Russian servicemen, it would mean
that the Russians, having gathered 200,000 servicemen for the
invasion, planned irreversible losses at the level of 22.5% and total
losses at the level of 90% of the total number of the invasion force,
which is unrealistic.

** State propaganda in the Russian Federation

Calls for the forced division/redistribution of the territory of
Ukraine, as well as for the murder of Ukrainian citizens can be found
in the following public materials:

- [[http://kremlin.ru/events/president/news/66181][Vladimir Putin's article "On the historical unity of Russians and Ukrainians", July 12, 2021]], [[https://web.archive.org /web/20220331143857/http://kremlin.ru/events/president/news/66181][Web Archive]]
- [[https://actualcomment.ru/tumannoe-budushchee-pokhabnogo-mira-2202150925.html]["Foggy Future of the Obscene World", February 15, 2022]], [[https://web.archive.org/web /20220324051406/https://actualcomment.ru/tumannoe-budushchee-pokhabnogo-mira-2202150925.html][Web Archive]]
- [[https://actualcomment.ru/kuda-delsya-khaos-raspakovka-stabilnosti-2111201336.html]["Where did the chaos go? Unpacking stability", November 20, 2021]], [[https://web.archive .org/web/20220401131352/https://actualcomment.ru/kuda-delsya-khaos-raspakovka-stabilnosti-2111201336.html][Web Archive]]
- [[https://ria.ru/20220403/ukraina-1781469605.html]["What Russia should do with Ukraine", 04/03/2022]], [[https://web.archive.org/web/20220404140751 /https://ria.ru/20220403/ukraina-1781469605.html][Web Archive]], ([english translation](https://medium.com/@kravchenko_mm/what-should-russia-do-with-ukraine-translation-of-a-propaganda-article-by-a-russian-journalist-a3e92e3cb64))
- [[https://www.youtube.com/watch?v=njCjKWMy2n0&t=40s][Fragment of speech by M. Khazin at the meeting of the club "Russian Outlook" 12/23/2016]]

** Historical data on the modus operandi of Russians in Ukraine

The events of the last 8 years demonstrate the invariability of the
modus operandi of Russians in Ukraine during the last century:

1. [[https://tinyurl.com/d2s3mkbh][Creation of "people's republics" on the territory of Ukraine in
   1917-1918]].
2. [[https://www.istpravda.com.ua/articles/2019/03/12/153809/][Mass killings of Kyivites by Muravyov's troops]], [[https://tinyurl.com/bdf9ktxh][red terror]]. Quote:
   "The crime committed by the Bolsheviks in Kyiv is the execution of
   defenseless victims not for what they did, but for who they were,
   he answers because in the literature it is called genocidal
   strategy: intentional destroy of a specific group of people. In our
   case, there were two groups: representatives of the "old order" -
   the aristocracy, officials, generals, officers - and supporters of
   the UPR - politicians and military. In a more detailed analysis of
   metric data, it is possible there will be grounds to single out the
   third group - young men."
3. [[https://tinyurl.com/2p8r3r4y][The murder of Roman Shukhevych and annihilation of his body]]. The
   quote: "By memories of a former MGB officer who participated in the
   operation on capture of Shukhevich, March 9, 1950 received an order
   to remove the body of General "Taras Chuprynka", - Roman
   Shukhevich, - outside the West Ukraine and burn, and scatter the
   ashes. This is exactly what was done on on the left bank of the
   river Zbruch, opposite the town of Skala-Podolskaya. "

** British Intelligence Opinion

Chief of MI6 in his Twitter [[https://twitter.com/ChiefMI6/status/1510629183365517326][wrote]]:
#+BEGIN_QUOTE
We knew Putin’s invasion plans included summary executions by his
military and intelligence services.  The reports of execution-style
killings of civilians emerging from liberated areas are horrifying and
chilling.
#+END_QUOTE

