#+TITLE: Про *запланированные* массовые убийства на територии Украины
#+AUTHOR: Mykola Stryebkov
#+LATEX_HEADER: \usepackage[utf8]{inputenc}
#+LATEX_HEADER: \usepackage[T2A]{fontenc}
#+LATEX_HEADER: \usepackage[english,russian]{babel}
#+LATEX_HEADER: \usepackage{lcy}
#+LATEX_HEADER: \usepackage{textcomp}
#+LATEX_HEADER: \usepackage[margin=2cm]{geometry}

* Резюме

Массовые убийства граждан Украины силами вторжения РФ являются результатом
*предварительно спланированной операции по физическому истреблению
социально-активной прослойки украинского общества.*

"Заряженность" россиян на такие социальные чистки является, в частности,
следствием многолетней государственной пропаганды в РФ и неизменности их
modus operandi в Украине (см. ниже).

*Документ будет уточняться и дополняться по мере получения и обработке новых
данных.*

* Подтверждение

** Однообразие казней

Сходство и однообразие казней разных людей в разных населенных пунктах
говорит об их выполнении согласно единой методике.

Таким образом, среди массовых убийств мирных жителей Киевской области явно
выделяются убийства людей, - преимущественно мужчин призывного возраста, -
со связанными за спиной руками и шаровым отверствием в затылке.

Задача: проверить существование соответствующей методической литературы в
силовых структурах РФ.

** ГОСТ Р 42.7.01-2021 на массовые захоронениея

Новый ГОСТ РФ о массовых захоронениях был принят в сентябре 21-го года и
введет в действие 1-го февраля 2022 года, чуть больше, чем за 3 недели
вплоть до начала открытой войны: [[https://docs.cntd.ru/document/1200180859][НАЦИОНАЛЬНЫЙ СТАНДАРТ РОССИЙСКОЙ ФЕДЕРАЦИИ. ЗАХОРОНЕНИЕ СРОЧНОЕ ТРУПОВ В ВОЕННОЕ И МИРНОЕ ВРЕМЯ]], [[https://web.archive.org/web/20220402173717/https://docs.cntd.ru/document/1200180859][Web Archive]].

Задача: проверить размеры массового захоронения в Буче. По ихнему
стандарту должно быть:
- 20м - длина по низу
- 3м - ширина
- 2.3м - глубина
- 32м - по верху с учетом склонов для выезда трактора

** Мобильные крематории

Предназначались во избежание захоронений публичных и общественных деятелей
Украины, поскольку публично известные места захоронения со временем создают
"места паломничества" (modus operandi аналогичен убийству Романа Шухевича
см. ниже).

О подготовке мобильных крематориев для вторжения в Украину армией
РФ за сутки до вторжения заявил Министр Обороны Великобритании Ben
Wallace. Об этом написал, в частности, [[https://www.telegraph.co.uk/world-news/2022/02/23/russia-deploys-mobile-crematorium-follow-troops-battle/][The Telegraph]] ([[https://web.archive.org/web/20220331033347/https://www.telegraph.co.uk/world-news/2022/02/23/russia-deploys-mobile-crematorium-follow-troops-battle/][We Archive]]). Правда, господин Walles
ошибочно решил, что с их помощью армия РФ собирается скрывать собственные
потери.

Подтверждениями тезиса о том, что крематории предназначались не для русских
солдат могут служить следующие факты:

- там, где армия РФ вообще собирала трупы своих, был отлажен их
  вывоз за пределы Украины.
- использование моб. крематориев для массового сожжения тел является
  нерациональным из-за характеристик, [[http://turmalin.su/index.php?option=com_content&view=article&id=185&Itemid=331][заявленные производителем]]:

#+BEGIN_QUOTE
При использовании в ритуальных целях:

- время полной кремации одного объекта: около 1 часа
- выгрузка праха автоматизирована
- кремуляция
- система дополнительной пылеочистки
- 15-16 литров дизтоплива или 20 м3 природного газа на кремацию одного объекта
#+END_QUOTE

** 45000 мешков для трупов

Мешки предназначались для граждан Украины.

Если бы мешки предназначались для трупов военнослужащих РФ, то это бы
значило, что россияне, собрав 200 тысяч для вторжения, запланировали
безвозвратные потери на уровне 22.5% и полные потери на уровне 90% от
общей численности группировки, что является нереальным.

** Государственная пропаганда в РФ

В приведенных ниже публичных материалах присутствуют призывы к принудительному
разделению/передела территории Украины, а также к убийствам граждан
Украины.

- [[http://kremlin.ru/events/president/news/66181][Статья Владимира Путина "Об историческом единстве русских и украинцев", 12 июля 2021 года]],  [[https://web.archive.org/web/20220331143857/http://kremlin.ru/events/president/news/66181][Web Archive]]
- [[https://actualcomment.ru/tumannoe-budushchee-pokhabnogo-mira-2202150925.html]["Туманное будущее похабного мира", 15 февраля 2022]],  [[https://web.archive.org/web/20220324051406/https://actualcomment.ru/tumannoe-budushchee-pokhabnogo-mira-2202150925.html][Web Archive]]
- [[https://actualcomment.ru/kuda-delsya-khaos-raspakovka-stabilnosti-2111201336.html]["Куда делся хаос? Распаковка стабильности", 20 ноября 2021]],   [[https://web.archive.org/web/20220401131352/https://actualcomment.ru/kuda-delsya-khaos-raspakovka-stabilnosti-2111201336.html][Web Archive]]
- [[https://ria.ru/20220403/ukraina-1781469605.html]["Что Россия должна сделать с Украиной", 03.04.2022]],   [[https://web.archive.org/web/20220404140751/https://ria.ru/20220403/ukraina-1781469605.html][Web Archive]]
- [[https://www.youtube.com/watch?v=njCjKWMy2n0&t=40s][Фрагмент выступления М. Хазина на заседании клуба «Русский кругозор» 23.12.2016]]

** Исторические данные о modus operandi россиян в Украине

События последних 8 лет демонстрируют неизменность modus operandi россиян
в Украине на протяжении последнего столетия:

1. [[https://tinyurl.com/d2s3mkbh][Создание "народных республик" на территории Украины в 1917-1918 годах]].
2. [[https://www.istpravda.com.ua/articles/2019/03/12/153809/][Массовые убийства киевлян войсками Муравьева]], [[https://tinyurl.com/bdf9ktxh][красный террор]]. Цитата:
   "Совершенное большевиками в Киеве преступление – расстрел беззащитных жертв
   не за то, что они совершили, а за то, кем они были, отвечает
   о том, что в литературе называется геноцидной стратегией: намерением
   уничтожить конкретную группу людей. В нашем случае речь шла о двух таких
   группах: представителей "старого порядка" – аристократии, чиновников,
   генералитета, офицеров – и сторонников УНР – политиков и
   военных. При более детальном анализе данных метрик, возможно,
   будут основания выделить третью группу – молодых мужчин."
3. [[https://tinyurl.com/2p8r3r4y][Убийство и уничтожение тела Романа Шухевича]]. Цитата : "По
   воспоминаниям бывшего офицера МГБ, участвовавшего в операции по
   захвату Шухевича, 9 марта 1950 года был получен приказ вывезти тело
   генерала «Тараса Чупрынки» — Романа Шухевича за пределы Западной
   Украины и сжечь, а пепел развеять. Именно это и было сделано на
   левом берегу реки Збруч, напротив города Скала-Подольская."

** Мнение британской разведки

Шеф британской военной разведки MI6 написал, что они имели информацию
о запланированных внесудебных убийствах еще до вторжения:
#+BEGIN_QUOTE
We knew Putin’s invasion plans included summary executions by his military and intelligence services. 
The reports of execution-style killings of civilians emerging from liberated areas are horrifying and chilling.
#+END_QUOTE
https://twitter.com/ChiefMI6/status/1510629183365517326
