#+TITLE: *Planning* of mass execution on the territory of Ukraine
#+AUTHOR: Mykola Stryebkov
#+LATEX_HEADER: \usepackage[utf8]{inputenc}
#+LATEX_HEADER: \usepackage[T2A]{fontenc}
#+LATEX_HEADER: \usepackage[english,ukrainian]{babel}
#+LATEX_HEADER: \usepackage{lcy}
#+LATEX_HEADER: \usepackage{textcomp}
#+LATEX_HEADER: \usepackage[margin=2cm]{geometry}

* Table of Content

Mass executions of Ukrainian citizens by Russian invasion forces are the result of
*premeditated operation with the goal of eliminating socaially active class of Ukrainian
society*

Willingness of Russians to carry out such actions is in part the result of
prolonged propaganda campaign by the Russian state and its consistent modus operandi
in Ukraine (see below).

*This document is work in progress and will be expanded accordingly.*

* Evidence

** Uniformity of the executions

The fact that the executions were carried out in the same or similar manner
accross wide geographicall area points out to the use of the same methodology.

For example, hands tied behind their back and a gunshot to the back of their head
is a clear pattern visible among civilians executed in the Kyiv region predominatelly
a military age males.

Goal: verify presence of the relevant procedural documentation in 
Russian Armed Forces.

** GOST[Russian equivalent of ISO]  R 42.7.01-2021 about mass burials 

New GOST about mass burials has been adopted in September of 2021 and 
enacted on February 1st of 2022 which is 3 weeks before the invasion 
of Ukraine.

Task: Check the dimensions of mass grave in Bucha. According to the GOST,
the imensions should be:
- 20m length
- 3m width
- 2.3m depth

** Mobile crematoriums

The goal of mobile crematoriums is to avoid having burial sites for the 
Ukrainian public figures since such sites become landmarks over time (
modus operandi that had been used after killing Roman Schuhevych, see below).

A day before the invasion, Secretary of State for Defence of the UK 
Ben Wallace mentioned about preparation of mobile crematoriums by Russia. See 
here: [[https://www.telegraph.co.uk/world-news/2022/02/23/russia-deploys-mobile-crematorium-follow-troops-battle/][The Telegraph]].
Mr Wallace mistankenly assumed that such crematoriums are to be used to
conseal Russian casualties.

The following shows that the creamatoriums were not for disposing Russian casualties:   

- Logistics of transporting the bodies to the outside of the Ukrainian territory  
were established in the battle areas where Russia collected their dead. 
- Using mobile crematoriums for mass disposal of bodies is inneficient
  due to the specifications of such creamtoriums [[http://turmalin.su/index.php?option=com_content&view=article&id=185&Itemid=331]:
+BEGIN_QUOTE
Specs:

- Cremation for a single body: around 1 hour
- automated unloading of the ashes
- cremulator
- additional dust cleaning system
- 15-16 l of diesel or 20-30 m3 of natural gas is used for a single creamation
#+END_QUOTE

** 45000 body bags
Body bags were for the Ukrainian citizens.

If body bags were for the Russian KIAs, this would imply that the
russians, with 200,000 invasion force, have planned 22.5% KIA and about
90% casualties which is not sustainable.

** Russian state propaganda
Public sources listed below call for the forced division of Ukrainian territory 
and also killing of ukrainian citizens.
- http://kremlin.ru/events/president/news/66181
- https://actualcomment.ru/tumannoe-budushchee-pokhabnogo-mira-2202150925.html
- https://actualcomment.ru/kuda-delsya-khaos-raspakovka-stabilnosti-2111201336.html
- https://ria.ru/20220403/ukraina-1781469605.html
- https://www.youtube.com/watch?v=njCjKWMy2n0&t=40s

** Historical data to Russian modus operandi in Ukraine

The last 8 years show that the Russian mous operandi in Ukraine has 
remained unchanged for the last century
1. [[https://tinyurl.com/d2s3mkbh][Creation of "people's republics" on the Ukrainian territory in 1917-1918]].
Quote:
  "The crime commited by Bolsheviks in Kyiv - execution of victims not for
  what they have done, but for who they were - is consistent with textbook definition of
  genocide: intentional elimination of the particular group of people. in our case,
  two such groups were targeted: representatives of the "old order" - aristocracy,
  bureaucrats, miliraty - and supporters of UNR - political and military figures. Upon further
  examination, the third group might be identified - young males."
  
3. [[https://tinyurl.com/2p8r3r4y][Murder of Roman Schyhevych and disposal of his body]]. Quote:
"According to the former MGB office who participated in caapture of Schyhevych,
  they received an order on March 9th 1950 to transport Schyhevych's body outside of the 
  Western Ukraine, burn it, and dispose the ashes. The order had been carried out east 
  of Zbruch river in the vicinity of Skala-Podolska 

** The UK intelligence assessment

MI6 chief posted that they had had information about planned extrajudicial 
executions before the invasion.
https://twitter.com/ChiefMI6/status/1510629183365517326
