#+TITLE: Notes about *organization* of massacres on the territory of Ukraine
#+AUTHOR: Mykola Stryebkov
#+LATEX_HEADER: \usepackage[utf8]{inputenc}
#+LATEX_HEADER: \usepackage[T2A]{fontenc}
#+LATEX_HEADER: \usepackage[english,ukrainian]{babel}
#+LATEX_HEADER: \usepackage{lcy}
#+LATEX_HEADER: \usepackage{textcomp}
#+LATEX_HEADER: \usepackage[margin=2cm]{geometry}

* Abstract

Mass killings of Ukraine citizens by Russia's invading forces are the results
of the pre-planned operation assuming physical extermination of the most socially
active layer of Ukrainian society.

Active involvement of Russians in those kind of repressions is, in fact, a direct
consequence of long-term government-approved propaganda in Russia and immutability
of their 'modus operandi' in Ukraine.

*This document will be updated and corrected as new facts are made public and processed.*

* Proofs

** Uniformity of the cases

Uniformity and similarity of the cases (deaths of the peoples 
at the very different settlements) testifies to execution of the massacres 
according to single one, unified and common plan. 

In particular, alongside mass murders of civil inhabitants of Kyiv region,
there are clearly distinguishable the murders of mainly male men of military age,
immobilized (laying and having their arms tied) and killed from behind
(shot in the back of the head).

The goal of the paper is to check the existence in russian special services
of corresponding documents (guides, manuals etc.) deccribing the methodology 
of performing such kind of mass murders.

** ГОСТ Р 42.7.01-2021 (GOST standard describing mass graves)

A new GOST standard was accepted on 21st of September, 2021, and has has entered 
into force at 1st of February, 2022, almost three weeks before the open war started: 
[[https://docs.cntd.ru/document/1200180859][НАЦИОНАЛЬНЫЙ СТАНДАРТ РОССИЙСКОЙ ФЕДЕРАЦИИ. ЗАХОРОНЕНИЕ СРОЧНОЕ ТРУПОВ В ВОЕННОЕ И МИРНОЕ ВРЕМЯ (Russian Federation National Standard. Immediate and Urgent Corpses Burial in Wartime and Peacetime)]], [[https://web.archive.org/web/20220402173717/https://docs.cntd.ru/document/1200180859][Web Archive]].

The goal of the section is to check the dimensions of mass graves in Bucha.
According to the standard, the dimensions should be, approximately:
- 20 meters (66 feet) - the length at the bottom of the pit (mass grave);
- 3 meters (10 feet) - width of the pit;
- 2.3 meters (7 feet) - depth of the pit;
- 32 meters - length of the burial 'on surface', counting the hills required 
for the excavators operation.

** Mobile Crematoria

Mobile Crematoria were used in order to hide burial places of ukrainian public
and social activists, as these kind of places known to public typically 
after the lapse oof time become the places of national pilgrimage 
('modus operandi' identical to the murder case of Roman Schuchevich,
see below).

Ben Wallace, Great Britain Minister of Defence, has stated about russian army 
preparing mobile crematoria for operations just the day before the invasion.
This was mentioned alongside from the other sources in [[https://www.telegraph.co.uk/world-news/2022/02/23/russia-deploys-mobile-crematorium-follow-troops-battle/][The Telegraph]] ([[https://web.archive.org/web/20220331033347/https://www.telegraph.co.uk/world-news/2022/02/23/russia-deploys-mobile-crematorium-follow-troops-battle/][We Archive]]).
We believe however that sir Wallace has wrongly decided that russian army will use mobile crematoria
in order to hide its own battle losses.

As an evidences of thesis that the mobile crematoria were used for civilians are:

- in those cases whereas russian army even has collected the corpses of their soldiers, the logistics
of exporting the copses of their dead soldiers outside of Ukraine worked properly;
- the usage of mobile crematoriaum is irrational due to its characteristics,
[[http://turmalin.su/index.php?option=com_content&view=article&id=185&Itemid=331][given by the manufacturer]]: 
#+BEGIN_QUOTE
...For the ritual purposes:

- Time of full cremation of single object: about 1 hour
- Unloading of the ashes is automatized
- Cremulation (bones shredding) is available
- Additional, dust cleaning system is installed
- 15-16 liters (about 4.22 US gal, 3.52 imp gal) of diesel fuel, or 20m3 of 
natural gas is consumed for the cremation of a single object
#+END_QUOTE

** 45000 body bags

We believe that 45000 body bags were designated for ukrainian citizens,
not for the russian soldiers which would die during the battles.

Otherwise, the fact that 45,000 body bags were prepaired would prove that
the russian troops counting 200,000 involved in invasion have pre-planned
irreversible losses of their own troops killed in action on the level of 22.5%,
and a full-losses (including injured and missing) reaching 90% of their troops,
which is irreal.

** Government Propaganda in Russian Federation

Publicly available sources (articles etc.) containing justification and
moral legalization of Ukraine crushing and separation, as also
the legalization of murders of Ukraine citizens, are listed below:

- [[http://kremlin.ru/events/president/news/66181][Vladimir Putin's article "About historical unity of russians and ukrainians", 12th of July 2021]],  [[https://web.archive.org/web/20220331143857/http://kremlin.ru/events/president/news/66181][Web Archive]]
- [[https://actualcomment.ru/tumannoe-budushchee-pokhabnogo-mira-2202150925.html]["Bawdy world's hazy future", 15th of February 2022]],  [[https://web.archive.org/web/20220324051406/https://actualcomment.ru/tumannoe-budushchee-pokhabnogo-mira-2202150925.html][Web Archive]]
- [[https://actualcomment.ru/kuda-delsya-khaos-raspakovka-stabilnosti-2111201336.html]["Where has gone the Chaos? Unpacking the Stability", 20th of November 2021]],   [[https://web.archive.org/web/20220401131352/https://actualcomment.ru/kuda-delsya-khaos-raspakovka-stabilnosti-2111201336.html][Web Archive]]
- [[https://ria.ru/20220403/ukraina-1781469605.html]["What Russia should make with Ukraine", 03.04.2021]],   [[https://web.archive.org/web/20220404140751/https://ria.ru/20220403/ukraina-1781469605.html][Web Archive]]
- [[https://www.youtube.com/watch?v=njCjKWMy2n0&t=40s][Fragment of the M. Chazin's speech during the "Russian Horizon" club meeting]]

** Historical data regarding modus operandi of russians in Ukraine

Events happening during the last 8 years clearly testify to the fact that 
modus operandi of the russians in Ukraine hasn't even slightly changed alongside the last century:

1. [[https://tinyurl.com/d2s3mkbh][Creation of the so-called 'people's republics' at the Ukrainian territory]].
2. [[https://www.istpravda.com.ua/articles/2019/03/12/153809/][Massacres of Kyiv dwellers performed by the Muraviov's troops]], [[https://tinyurl.com/bdf9ktxh][Red terror]]. Quote:
   "The crime performed by Bolsheviks in Kyiv - execution of unarmed victims
   not by the fact what they have done, but by whom they were - corresponds to which
   in literature is called as 'genocidal strategy': an intention to exterminate
   certain group of the population. In our case, there were two of the groups:
   the representatives of 'the old order' - aristocracy, offciary, generals and officers - 
   and Ukrainian People's Republic (UNR) supporters - politicians and military men.
   On closer examination of the data metrics, it may be reasonable to distinguish 
   a third group consisting of young men."
3. [[https://tinyurl.com/2p8r3r4y][Roman Shukhevych murder and disposal of the body]]. Quote: 
   "According to the recollections of a former MGB (Ministry of State Security)
   officer who participated in Shukhevych Capture operation, on 9th of March, 1950,
   an order was received to take the body of General "Taras Chuprynka" - Roman Shukhevych, 
   out of Western Ukraine and burn it, and dispel the ashes. This is exactly what
   was done on the left bank of the Zbruch River, opposite side to the town of Skala-Podolskaya."

** British intelligence opinion

MI6 chief agency executive has wrote: 
#+BEGIN_QUOTE
We knew Putin’s invasion plans included summary executions by his military and intelligence services. 
The reports of execution-style killings of civilians emerging from liberated areas are horrifying and chilling.
#+END_QUOTE
https://twitter.com/ChiefMI6/status/1510629183365517326
